### ISSUE TITLE
intersections

### ISSUE THREAD

**Issue by bluelemonade** [mathigon/euclid.js#131]
I tried following snippet:
        
const ellipse = new Ellipse(new Point(100, 100), 5, 3, 0); 
const pt = new Point(100,100);
console.log("RESULT", intersections(pt, ellipse).length)

Ithe point is inside the ellipse, but the elngth of the intersections() is 0. how to use this correctly?

**Comment by plegner** [comment]
The `intersections` function only finds intersections between lines or boundaries (e.g. the boundary of a circle and a line segment). It also doesn't support ellipses, because of the complexity of the maths involved.

To check if an ellipse contains a point, you can use the `Ellipse.contains(p: point)` method.
