### ISSUE TITLE
Calling drawCanvas with a line doesn't seem to work

### ISSUE THREAD

**Issue by macu** [mathigon/euclid.js#88]
Calling drawCanvas with a line doesn't work.

```js
drawCanvas(this.context2d, new Line(new Point(100, 100), new Point(200, 100)), {
	stroke: 'orange',
	strokeWidth: 3,
});
```

**Comment by fmeyszies** [comment]
+1, not working for me either. Have not found any way to make it work yet.

**Comment by plegner** [comment]
Added in https://github.com/mathigon/euclid.js/commit/e29e12114cec461abb40f9ff650c418981e7a0ae – thanks for suggesting!

Please note that in order to draw Rays or Lines, you need to pass a `box` property for `CanvasDrawingOptions`, which is a Rectangle representing the outer bounds of the canvas. This is needed for drawing infinite `Line`s and `Ray`s, but not finite line `Segment`s, which were already supported.
